### ISSUE TITLE
Use qemu-exit

### ISSUE THREAD

**Issue by Skallwar** [repnop/vanadinite#1]
I saw this comment: https://github.com/repnop/vanadinite/blob/1c66cb07ec4418a1806f41b589da13e469ab0441/src/vanadinite/src/arch/virt/mod.rs#L38

You might be intrested in https://github.com/andre-richter/qemu-exit

**Comment by repnop** [comment]
I don't think its particularly worth it since I only care about the RISC-V specifics and the code is already written, but I appreciate being made aware of that crate, thanks! :)
