### ISSUE TITLE
cargo xtask run => execute qemu fail

### ISSUE THREAD

**Issue by wei-huan** [repnop/vanadinite#4]
I think the problem is that I don't have the file: nettraffic.dat. Because .gitignore shields the testing_files directory to github server.

This is the last output in console when I run `cargo xtask run`

$ git submodule init submodules/opensbi
$ git submodule update --remote submodules/opensbi
$ make PLATFORM=generic FW_PIC=no FW_PAYLOAD_PATH=../../src/kernel/target/riscv64gc-unknown-none-elf/release/vanadinite.bin
 AS        platform/generic/firmware/fw_payload.o
 ELF       platform/generic/firmware/fw_payload.elf
 OBJCOPY   platform/generic/firmware/fw_payload.bin
$ qemu-system-riscv64 -machine virt -cpu rv64 -smp 4 -m 512M -append  -global virtio-mmio.force-legacy=false -netdev user,id=net1,hostfwd=udp:127.0.0.1:1111-10.0.2.15:1337 -device virtio-net-device,netdev=net1 -object filter-dump,id=f1,netdev=net1,file=testing_files/nettraffic.dat -bios build/opensbi-riscv64-generic-fw_jump.elf -kernel src/kernel/target/riscv64gc-unknown-none-elf/release/vanadinite -serial mon:stdio -nographic
qemu-system-riscv64: -object filter-dump,id=f1,netdev=net1,file=testing_files/nettraffic.dat: net dump: can't open testing_files/nettraffic.dat: No such file or directory
Error: command `qemu-system-riscv64 -machine virt -cpu rv64 -smp 4 -m 512M -append  -global virtio-mmio.force-legacy=false -netdev user,id=net1,hostfwd=udp:127.0.0.1:1111-10.0.2.15:1337 -device virtio-net-device,netdev=net1 -object filter-dump,id=f1,netdev=net1,file=testing_files/nettraffic.dat -bios build/opensbi-riscv64-generic-fw_jump.elf -kernel src/kernel/target/riscv64gc-unknown-none-elf/release/vanadinite -serial mon:stdio -nographic` failed, exit status: 1

**Comment by repnop** [comment]
Hi, sorry for the late reply, but as the error suggests, you need to create a `testing_files` directory :+1: I'm still heavily in a experimenting and testing phase with `vanadinite` so that is a directory I use to keep files that I use for debugging in so that they don't get committed for the time being!

**Comment by wei-huan** [comment]
Thanks for solution
